### ISSUE TITLE
Support for PnP?

### ISSUE THREAD

**Issue by dotansimha** [urish/java-ast#14]
[Yarn 2 supports PnP modules](https://yarnpkg.com/features/pnp), and it seems like the integration of this library and `antlr4ts` causes issues :

```
  ● Test suite failed to run

    TypeError: Class extends value undefined is not a constructor or null

      at Object.<anonymous> (.yarn/cache/antlr4ts-npm-0.5.0-dev-7e0fc8988a-0f206ef5ef.zip/node_modules/src/tree/xpath/XPathLexer.ts:18:33)
      at Object.<anonymous> (.yarn/cache/antlr4ts-npm-0.5.0-dev-7e0fc8988a-0f206ef5ef.zip/node_modules/src/tree/xpath/XPath.ts:16:1)
``` 

Was unable to debug and check why, but without PnP it seems to work correctly. 

And idea?

**Comment by urish** [comment]
Hi Dotan, it seems like the issue comes from [antlr4ts](https://github.com/tunnelvisionlabs/antlr4ts), I suggest that you open an issue there.
